# Site settings
title: Iwen Su
email: isu@bren.ucsb.edu
url: https://iwensu0313.github.io
description: "Find out more about projects I've been involved in and my prior work experiences."

# Image logo (top left)
title-img: /img/profile.jpg


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#023742'
  links: '#219ab3'

# Footer settings
footer: Iwen Su, <a href="http://jeromelachaud.github.io/grayscale-theme/">Grayscale theme</a>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/iwen_su
  - title: linkedin
    url: https://www.linkedin.com/in/iwensu
  - title: github
    url: https://github.com/iwensu0313

# Build settings
markdown: kramdown
permalink: pretty
